#include "ILlmBackend.hpp"
#include "Qwen3Backend.hpp"

#include "llama.h"
#include "llama-cpp.h"

#include <algorithm>
#include <cstdint>
#include <format>
#include <memory>
#include <mutex>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

class Qwen3Backend : public ILlmBackend {
private:
    // generated *once* in constructor
    llama_model_ptr _model;
    const llama_vocab* _vocab;
    llama_context_ptr _context; // owns the KV cache
    llama_sampler_ptr _sampler;
    const char* _chatTemplate;  // from the model GGUF

    // (re-)generated by createFreshContext; updated by synthesizeToQueue
    std::vector<std::pair<std::string, std::string>> _history; // [(role, content)]
    std::string _lastFormatted;

    std::mutex _mutex;
    bool _cancelled = false;

    void tokenizeAndCache(const std::string& buffer, bool freshContext) {
        // guess extra buffer (otherwise resize in next step)
        std::vector<llama_token> tokens(buffer.size() + 8);

        int32_t count = llama_tokenize(
            _vocab,
            buffer.data(),
            (int32_t)buffer.size(),
            tokens.data(),
            (int32_t)tokens.size(),
            freshContext,
            true);
        
        if (count < 0) {
            // hint by the llama ABI that resize is needed
            tokens.resize(-count);
            count = llama_tokenize(
                _vocab,
                buffer.data(),
                (int32_t)buffer.size(),
                tokens.data(),
                (int32_t)tokens.size(),
                freshContext,
                true);
        }

        tokens.resize(count);

        // prefill in n_batch chunks
        const int32_t n_batch = (int32_t)llama_n_batch(_context.get());
        for (int32_t i = 0; i < count; i += n_batch) {
            int32_t chunk = std::min(n_batch, count - i);
            llama_batch batch = llama_batch_get_one(tokens.data() + i, chunk);
            if (llama_decode(_context.get(), batch) != 0) {
                throw std::runtime_error(std::format("llama_decode failed on batch {}/{}", i, count));
            }
        }
    }

public:
    Qwen3Backend(const std::string& modelPath) {
        // backend init is required only *once per codebase*
        llama_backend_init();
        
        llama_model_params modelParams = llama_model_default_params(); // tune as needed
        llama_model* modelPtr = llama_model_load_from_file(modelPath.c_str(), modelParams);
        if (!modelPtr) {
            throw std::runtime_error(std::format("failed to load model: {}", modelPath));
        }
        
        _model = llama_model_ptr(modelPtr);
        _vocab = llama_model_get_vocab(_model.get());

        llama_context_params contextParams = llama_context_default_params(); // tune as needed
        _context = llama_context_ptr(llama_init_from_model(modelPtr, contextParams));

        llama_sampler_chain_params samplerParams = llama_sampler_chain_default_params();
        llama_sampler* samplerPtr = llama_sampler_chain_init(samplerParams);

        // for the sampler chain, do *not* use the default (greedy) chain, because it always only picks the most probably token
        llama_sampler_chain_add(samplerPtr, llama_sampler_init_top_k(50));
        llama_sampler_chain_add(samplerPtr, llama_sampler_init_top_p(.95, 1));
        llama_sampler_chain_add(samplerPtr, llama_sampler_init_temp(.8));
        llama_sampler_chain_add(samplerPtr, llama_sampler_init_dist(LLAMA_DEFAULT_SEED));
        _sampler = llama_sampler_ptr(samplerPtr);

        _chatTemplate = llama_model_chat_template(_model.get(), nullptr);
    }

    ~Qwen3Backend() override {
        // backend shutdown *once, globally*
        llama_backend_free();
    }

    void createFreshContext(const std::string& systemPrompt) override {
        std::lock_guard lock(_mutex);

        // wipe decoded tokens & sampler state
        llama_memory_clear(llama_get_memory(_context.get()), true);
        llama_sampler_reset(_sampler.get());

        _history.clear();
        _history.emplace_back("system", systemPrompt);
        _lastFormatted.clear();

        // prime KV cache w/ new system prompt
        std::vector<llama_chat_message> messages;
        for (std::pair<std::string, std::string>& [role, content] : _history) {
            messages.push_back({role.c_str(), content.c_str()});
        }

        // estimate buffer (otherwise a resize happens; also okay)
        std::string buffer(systemPrompt.length() + 128, '\0');
        int32_t size = llama_chat_apply_template(
            _chatTemplate,
            messages.data(),
            messages.size(),
            false,
            buffer.data(),
            buffer.size());
        
        if (size < 0) {
            throw std::runtime_error("failed to apply system prompt");
        }

        if ((size_t)size > buffer.size()) {
            buffer.resize(size);
            llama_chat_apply_template(
                _chatTemplate,
                messages.data(),
                messages.size(),
                false,
                buffer.data(),
                size);
        }
            
        buffer.resize(size);
        _lastFormatted = buffer;

        // prepare the KV cache
        tokenizeAndCache(buffer, true);
    }

    /// @copydoc ILlmBackend::warmup
    void warmup() override {
        ;
    }
    
    /// @copydoc ILlmBackend::synthesizeToQueue
    void synthesizeToQueue(const std::string &prompt, BlockingQueue<std::string> &queue) override {
        ;
    }
    
    /// @copydoc ILlmBackend::cancel
    void cancel() override {
        ;
    }
};

std::unique_ptr<ILlmBackend> createQwen3Backend(const std::string &modelPath) {
    return std::make_unique<Qwen3Backend>(modelPath);
}
