#include "ILlmBackend.hpp"
#include "Qwen3Backend.hpp"

#include "llama.h"
#include "llama-cpp.h"

#include <algorithm>
#include <atomic>
#include <cstdint>
#include <cstdio>
#include <format>
#include <memory>
#include <mutex>
#include <optional>
#include <print>
#include <ranges>
#include <span>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

/// @brief Interfaces with Qwen3 in llama.cpp. *Only one instance* must ever exist per codebase.
class Qwen3Backend : public ILlmBackend {
private:
    // spins up & winds down the whole llama.cpp backend
    BackendLifetime _lifetime;

    // generated *once* in constructor
    llama_model_ptr _model;
    const llama_vocab* _vocab;
    llama_context_ptr _context; // owns the KV cache
    llama_sampler_ptr _sampler;
    const char* _chatTemplate;  // from the model GGUF

    // (re-)generated by createFreshContext; updated by synthesizeToQueue
    std::vector<std::pair<std::string, std::string>> _history; // [(role, content)]
    std::string _lastFormatted;
    std::atomic<bool> _cancelled = false;
    std::mutex _ctxMutex;

    std::string getHistoryFormatted(bool addAssistant) {
        std::vector<llama_chat_message> messages;
        for (auto&& [role, content] : _history) {
            messages.push_back({role.c_str(), content.c_str()});
        }

        // estimate buffer (otherwise a resize happens; also okay)
        std::string chatBuffer(_lastFormatted.size() + 128, '\0');
        int32_t size = llama_chat_apply_template(
            _chatTemplate,
            messages.data(),
            messages.size(),
            addAssistant,
            chatBuffer.data(),
            chatBuffer.size());
        
        if (size < 0) {
            throw std::runtime_error("failed to format chat history");
        }

        if (size > chatBuffer.size()) {
            chatBuffer.resize(size);
            llama_chat_apply_template(
                _chatTemplate,
                messages.data(),
                messages.size(),
                addAssistant,
                chatBuffer.data(),
                size);
        }

        chatBuffer.resize(size);
        return chatBuffer;
    }

    /// @brief Tokenize an LLM input.
    std::vector<llama_token> tokenize(const std::string& llmIn, bool freshContext) {
        // guess extra buffer (otherwise resize in next step)
        std::vector<llama_token> tokens(llmIn.size() + 8);

        int32_t count = llama_tokenize(
            _vocab,
            llmIn.data(),
            (int32_t)llmIn.size(),
            tokens.data(),
            (int32_t)tokens.size(),
            freshContext,
            true);
        
        if (count < 0) {
            // hint by the llama ABI that resize is needed
            tokens.resize(-count);
            count = llama_tokenize(
                _vocab,
                llmIn.data(),
                (int32_t)llmIn.size(),
                tokens.data(),
                (int32_t)tokens.size(),
                freshContext,
                true);
        }

        if (count < 0) {
            throw std::runtime_error(std::format("tokenize failed (reported count: {})", count));
        }

        tokens.resize(count);
        return tokens;
    }

    int32_t decode(llama_batch& batch, int32_t batchSize, const std::vector<llama_token>& tokens) {
        // returns -1 on an empty sequence
        llama_pos startPos = llama_memory_seq_pos_max(llama_get_memory(_context.get()), 0);

        int32_t decodeStatus = -99;

        for (int i = 0; i < tokens.size(); i += batchSize) {
            // make sure to not exceed batch size per decode call
            size_t chunkLen = std::min((size_t)batchSize, tokens.size() - i);
            std::span<const llama_token> slice { tokens.begin() + i, chunkLen };
            
            for (auto&& [j, token] : std::views::enumerate(slice)) {
                batch.token[j] = token;
                batch.pos[j] = ++startPos;
                batch.n_seq_id[j] = 1;
                batch.seq_id[j][0] = 0;
        
                // whether to output per-vocab-token scores for this token (i.e. prediction for next token)
                batch.logits[j] = i + j == tokens.size() - 1;
            }
            
            batch.n_tokens = chunkLen;

            decodeStatus = llama_decode(_context.get(), batch);
            if (decodeStatus != 0) {
                return decodeStatus;
            }
        }
        
        return decodeStatus;
    }
    
    std::optional<llama_token> getNextToken(int32_t decodeResult) {
        std::optional<std::string> msg = std::nullopt;
    
        switch (decodeResult) {
            case 0:
                // idx=-1 returns the last token in the batch where logits=true
                return llama_sampler_sample(_sampler.get(), _context.get(), -1);
            
            case 1:
                msg = "could not find a KV slot for the batch (try reducing the size of the batch or increase the context)";
                break;
            
            case 2:
                msg = "generation aborted";
                break;
    
            case -1:
                msg = "invalid input batch";
                break;
    
            default:
                throw std::runtime_error(std::format("getNextToken fatal error (code {})", decodeResult));
        }
    
        std::println(stderr, "getNextToken problem: {}", msg.value_or("unknown"));
        return std::nullopt;
    }

    /// @brief Convert a single token to its text piece.
    std::string tokenToPiece(llama_token token) {
        // most pieces are a few bytes; resize below if not
        std::string piece(16, '\0');

        int32_t size = llama_token_to_piece(
            _vocab,
            token,
            piece.data(),
            (int32_t)piece.size(),
            0, // don't skip leading spaces
            false); // don't render <|im_end|> etc. into the text

        if (size < 0) {
            // hint by the llama ABI that resize is needed
            piece.resize(-size);
            size = llama_token_to_piece(_vocab, token, piece.data(), (int32_t)piece.size(), 0, false);
        }

        if (size < 0) {
            throw std::runtime_error(std::format("tokenToPiece (reported size: {})", size));
        }

        piece.resize(size);
        return piece;
    }

public:
    Qwen3Backend(const std::string& modelPath, int32_t contextSize) {
        std::lock_guard lock(_ctxMutex);

        llama_model_params modelParams = llama_model_default_params(); // tune as needed
        llama_model* modelPtr = llama_model_load_from_file(modelPath.c_str(), modelParams);
        if (!modelPtr) {
            throw std::runtime_error(std::format("failed to load model: {}", modelPath));
        }
        
        _model = llama_model_ptr(modelPtr);
        _vocab = llama_model_get_vocab(_model.get());

        llama_context_params contextParams = llama_context_default_params(); // tune as needed
        contextParams.n_ctx = contextSize;
        _context = llama_context_ptr(llama_init_from_model(modelPtr, contextParams));
        if (!_context.get()) {
            throw std::runtime_error(std::format("failed to init context from model: {}", modelPath));
        }

        llama_sampler_chain_params samplerParams = llama_sampler_chain_default_params();
        llama_sampler* samplerPtr = llama_sampler_chain_init(samplerParams);

        // for the sampler chain, do *not* use the default (greedy) chain, because it always only picks the most probably token
        llama_sampler_chain_add(samplerPtr, llama_sampler_init_top_k(50));
        llama_sampler_chain_add(samplerPtr, llama_sampler_init_top_p(.95, 1));
        llama_sampler_chain_add(samplerPtr, llama_sampler_init_temp(.8));
        llama_sampler_chain_add(samplerPtr, llama_sampler_init_dist(LLAMA_DEFAULT_SEED));
        _sampler = llama_sampler_ptr(samplerPtr);

        _chatTemplate = llama_model_chat_template(_model.get(), nullptr);
    }

    void createFreshContext(const std::string& systemPrompt) override {
        std::lock_guard lock(_ctxMutex);

        // wipe decoded tokens & sampler state
        llama_memory_clear(llama_get_memory(_context.get()), true);
        llama_sampler_reset(_sampler.get());

        _history.clear();
        _history.emplace_back("system", systemPrompt);
        _lastFormatted = getHistoryFormatted(false);

        int32_t batchSize = llama_n_batch(_context.get());
        llama_batch batch = llama_batch_init(batchSize, 0, 1);
        BatchCloser closer { batch };
        std::vector<llama_token> tokens = tokenize(_lastFormatted, true);
        int32_t status = decode(batch, batchSize, tokens);
        if (status != 0) {
            throw std::runtime_error(std::format("decoding system prompt failed with code {}", status));
        }

        _cancelled = false;
    }
    
    /// @copydoc ILlmBackend::warmup
    void warmup() override {
        std::lock_guard lock(_ctxMutex);

        struct Raii {
            llama_context* context;
            llama_sampler* sampler;

            ~Raii() {
                llama_memory_clear(llama_get_memory(context), true);
                llama_sampler_reset(sampler);
            }
        } raii { _context.get(), _sampler.get() };

        int32_t batchSize = llama_n_batch(_context.get());
        llama_batch batch = llama_batch_init(batchSize, 0, 1);
        BatchCloser closer { batch };

        std::vector<llama_token> tokens = tokenize("default", true);
        int32_t status = decode(batch, batchSize, tokens);
        if (status != 0) {
            throw std::runtime_error(std::format("warmup failed (code {})", status));
        }
    }
    
    /// @copydoc ILlmBackend::synthesizeToQueue
    void synthesizeToQueue(const std::string &prompt, BlockingQueue<std::string> &queue, int32_t maxTokens) override {
        std::lock_guard lock(_ctxMutex);
        
        _cancelled = false;

        // reuse for whole turn
        int32_t batchSize = llama_n_batch(_context.get());
        llama_batch batch = llama_batch_init(batchSize, 0, 1);

        QueueCloser qCloser { queue };
        BatchCloser bCloser { batch };

        _history.emplace_back("user", prompt);
        std::string formatted = getHistoryFormatted(true);

        // only process what's new
        if (formatted.starts_with(_lastFormatted)) {
            formatted = formatted.substr(_lastFormatted.size());
        }

        std::vector<llama_token> tokens = tokenize(formatted, false);

        bool stop = false;
        int32_t count = 0;
        std::string reply = "";

        while (!stop) {
            int32_t status = decode(batch, batchSize, tokens);
            std::optional<llama_token> next = getNextToken(status);
        
            bool isEog = llama_vocab_is_eog(_vocab, *next);

            stop = _cancelled || 
                !next || 
                isEog ||
                ++count > maxTokens;
            
            if (!stop) {
                tokens = { *next };
                std::string piece = tokenToPiece(*next);
                queue.push(piece);
                reply += piece;
            }

            if (isEog) {
                // decode the EOG token <|im_end|> so that KV cache is synced with history
                status = decode(batch, batchSize, { *next });
                if (status != 0) {
                    throw std::runtime_error(std::format("failed decode EOG (code {})", status));
                }
            }
        }
        
        _history.emplace_back("assistant", reply);
        _lastFormatted = getHistoryFormatted(false);
    }
    
    /// @copydoc ILlmBackend::cancel
    void cancel() override { _cancelled = true; }
};

std::unique_ptr<ILlmBackend> createQwen3Backend(const std::string &modelPath, int32_t contextSize) {
    return std::make_unique<Qwen3Backend>(modelPath, contextSize);
}
