#include "ILlmBackend.hpp"
#include "Qwen3Backend.hpp"

#include "llama.h"
#include "llama-cpp.h"

#include <algorithm>
#include <atomic>
#include <cstdint>
#include <cstdio>
#include <format>
#include <memory>
#include <mutex>
#include <optional>
#include <print>
#include <ranges>
#include <span>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

/// @brief Interfaces with Qwen3 in llama.cpp. *Only one instance* must ever exist per codebase.
class Qwen3Backend : public ILlmBackend {
private:
    // spins up & winds down the whole llama.cpp backend
    BackendLifetime _lifetime;

    // generated *once* in constructor
    llama_model_ptr _model;
    const llama_vocab* _vocab;
    llama_context_ptr _context; // owns the KV cache
    llama_sampler_ptr _sampler;
    const char* _chatTemplate;  // from the model GGUF

    // (re-)generated by createFreshContext; updated by synthesizeToQueue
    std::atomic<bool> _cancelled = false;
    std::mutex _ctxMutex;

    // reused batching
    int32_t _batchSize;
    llama_batch _batch;

    // state
    std::vector<std::pair<std::string, std::string>> _history; // [(role, content)]
    std::vector<llama_token> _committed; // what's actually in KV seq 0, positions [0, size())
    bool _kvUnknown = false; // e.g. after unsuccessful decode

    std::string getHistoryFormatted(bool addAssistant) {
        std::vector<llama_chat_message> messages;
        for (auto&& [role, content] : _history) {
            messages.push_back({role.c_str(), content.c_str()});
        }

        // estimate buffer (otherwise a resize happens; also okay)
        std::string chatBuffer(1024, '\0');
        int32_t size = llama_chat_apply_template(
            _chatTemplate,
            messages.data(),
            messages.size(),
            addAssistant,
            chatBuffer.data(),
            chatBuffer.size());
        
        if (size < 0) {
            throw std::runtime_error("failed to format chat history");
        }

        if (size > chatBuffer.size()) {
            chatBuffer.resize(size);
            llama_chat_apply_template(
                _chatTemplate,
                messages.data(),
                messages.size(),
                addAssistant,
                chatBuffer.data(),
                size);
        }

        chatBuffer.resize(size);
        return chatBuffer;
    }

    /// @brief Tokenize an LLM input.
    std::vector<llama_token> tokenize(const std::string& llmIn, bool freshContext) {
        // guess extra buffer (otherwise resize in next step)
        std::vector<llama_token> tokens(llmIn.size() + 8);

        int32_t count = llama_tokenize(
            _vocab,
            llmIn.data(),
            (int32_t)llmIn.size(),
            tokens.data(),
            (int32_t)tokens.size(),
            freshContext,
            true);
        
        if (count < 0) {
            // hint by the llama ABI that resize is needed
            tokens.resize(-count);
            count = llama_tokenize(
                _vocab,
                llmIn.data(),
                (int32_t)llmIn.size(),
                tokens.data(),
                (int32_t)tokens.size(),
                freshContext,
                true);
        }

        if (count < 0) {
            throw std::runtime_error(std::format("tokenize failed (reported count: {})", count));
        }

        tokens.resize(count);
        return tokens;
    }

    bool decode(const std::vector<llama_token>& tokens) {
        if (tokens.empty()) {
            return true;
        }
        
        // returns -1 on an empty sequence
        llama_pos startPos = (llama_pos)_committed.size();

        int32_t decodeStatus = -99;

        for (int i = 0; i < tokens.size(); i += _batchSize) {
            // make sure to not exceed batch size per decode call
            size_t chunkLen = std::min((size_t)_batchSize, tokens.size() - i);
            std::span<const llama_token> slice { tokens.begin() + i, chunkLen };
            
            for (auto&& [j, token] : std::views::enumerate(slice)) {
                _batch.token[j] = token;
                _batch.pos[j] = ++startPos;
                _batch.n_seq_id[j] = 1;
                _batch.seq_id[j][0] = 0;
        
                // whether to output per-vocab-token scores for this token (i.e. prediction for next token)
                _batch.logits[j] = i + j == tokens.size() - 1;
            }
            
            _batch.n_tokens = chunkLen;

            decodeStatus = llama_decode(_context.get(), _batch);
            if (decodeStatus != 0) {
                break;
            }
        }

        std::optional<std::string> reason = std::nullopt;
        switch (decodeStatus) {
            case 0:
                return true;
            
            case 1:
                reason = "could not find a KV slot for the batch (try reducing the size of the batch or increase the context)";
                break;
            
            case 2:
                reason = "generation aborted";
                break;
    
            case -1:
                reason = "invalid input batch";
                break;
    
            default:
                reason = std::format("fatal error (code {})", decodeStatus);
                break;
        }
        
        std::println(stderr, "decode failed: {}", reason.value_or("unknown"));
        _kvUnknown = true;
        return false;
    }
    
    /// @brief Compares _history and _committed and decodes everything that isn't committed yet.
    void decodeAllHistory(bool addAssistant) {
        std::vector<llama_token> historyTokens = tokenize(getHistoryFormatted(addAssistant), true);

        // ensure no context overrun
        const size_t tokenBudget = (size_t)(llama_n_ctx(_context.get()) * 0.8);
        while (historyTokens.size() > tokenBudget && _history.size() >= 4) {
            std::println(stderr, "history exceeds token budget {} - dropping oldest turn", historyTokens.size(), tokenBudget);
            // always keep [0] = system prompt
            _history.erase(_history.begin() + 1, _history.begin() + 3);
            historyTokens = tokenize(getHistoryFormatted(addAssistant), true);
        }

        llama_memory_t memory = llama_get_memory(_context.get());

        size_t sameCount = 0;
        if (!_kvUnknown) {
            size_t count = std::min(historyTokens.size(), _committed.size());
            while (sameCount < count && historyTokens[sameCount] == _committed[sameCount]) {
                sameCount++;
            }

            if (sameCount == historyTokens.size() && sameCount > 0) {
                sameCount--; // leave last token for logits
            }
        }
        
        if (_kvUnknown || !llama_memory_seq_rm(memory, 0, sameCount, -1)) {
            // try remove the identical part from memory
            // returns false on failure -> clear all memory in that case
            llama_memory_clear(memory, true);
            sameCount = 0;
        }

        _committed.resize(sameCount);
        _kvUnknown = false;

        // try decode delta between history & committed
        std::vector<llama_token> todoTokens(historyTokens.begin() + sameCount, historyTokens.end());
        if (!todoTokens.empty() && !decode(todoTokens)) {
            _kvUnknown = true; // rebuild from scratch on next reconcile (_history stays intact)
            throw std::runtime_error("prefill failed");
        }

        _committed = std::move(historyTokens);
    }

    /// @brief Convert a single token to its text piece.
    std::string tokenToPiece(llama_token token) {
        // most pieces are a few bytes; resize below if not
        std::string piece(16, '\0');

        int32_t size = llama_token_to_piece(
            _vocab,
            token,
            piece.data(),
            (int32_t)piece.size(),
            0, // don't skip leading spaces
            false); // don't render <|im_end|> etc. into the text

        if (size < 0) {
            // hint by the llama ABI that resize is needed
            piece.resize(-size);
            size = llama_token_to_piece(_vocab, token, piece.data(), (int32_t)piece.size(), 0, false);
        }

        if (size < 0) {
            throw std::runtime_error(std::format("tokenToPiece (reported size: {})", size));
        }

        piece.resize(size);
        return piece;
    }

public:
    Qwen3Backend(const std::string& modelPath, int32_t contextSize) {
        std::lock_guard lock(_ctxMutex);

        llama_model_params modelParams = llama_model_default_params(); // tune as needed
        llama_model* modelPtr = llama_model_load_from_file(modelPath.c_str(), modelParams);
        if (!modelPtr) {
            throw std::runtime_error(std::format("failed to load model: {}", modelPath));
        }
        
        _model = llama_model_ptr(modelPtr);
        _vocab = llama_model_get_vocab(_model.get());

        llama_context_params contextParams = llama_context_default_params(); // tune as needed
        contextParams.n_ctx = contextSize;
        _context = llama_context_ptr(llama_init_from_model(modelPtr, contextParams));
        if (!_context.get()) {
            throw std::runtime_error(std::format("failed to init context from model: {}", modelPath));
        }

        _batchSize = llama_n_batch(_context.get());
        _batch = llama_batch_init(_batchSize, 0, 1);

        llama_sampler_chain_params samplerParams = llama_sampler_chain_default_params();
        llama_sampler* samplerPtr = llama_sampler_chain_init(samplerParams);

        // for the sampler chain, do *not* use the default (greedy) chain, because it always only picks the most probably token
        llama_sampler_chain_add(samplerPtr, llama_sampler_init_top_k(50));
        llama_sampler_chain_add(samplerPtr, llama_sampler_init_top_p(.95, 1));
        llama_sampler_chain_add(samplerPtr, llama_sampler_init_temp(.8));
        llama_sampler_chain_add(samplerPtr, llama_sampler_init_dist(LLAMA_DEFAULT_SEED));
        _sampler = llama_sampler_ptr(samplerPtr);

        _chatTemplate = llama_model_chat_template(_model.get(), nullptr);
    }

    ~Qwen3Backend() override {
        llama_batch_free(_batch);
    }

    void createFreshContext(const std::string& systemPrompt) override {
        std::lock_guard lock(_ctxMutex);

        // wipe decoded tokens & sampler state
        llama_memory_clear(llama_get_memory(_context.get()), true);
        llama_sampler_reset(_sampler.get());

        _committed.clear();
        _kvUnknown = false;
        _history.clear();
        _history.emplace_back("system", systemPrompt);

        decodeAllHistory(false); // prefill the system prompt cache
        _cancelled = false;
    }
    
    /// @copydoc ILlmBackend::warmup
    void warmup() override {
        std::lock_guard lock(_ctxMutex);

        struct Raii {
            decltype(_context)& context;
            decltype(_sampler)& sampler;
            decltype(_kvUnknown) kvUnknown;

            ~Raii() {
                llama_memory_clear(llama_get_memory(context.get()), true);
                llama_sampler_reset(sampler.get());
                kvUnknown = true; // force rebuild next turn
            }
        } raii { _context, _sampler, _kvUnknown };

        decodeAllHistory(false);
    }
    
    /// @copydoc ILlmBackend::synthesizeToQueue
    void synthesizeToQueue(const std::string &prompt, BlockingQueue<std::string> &queue, int32_t maxTokens) override {
        std::lock_guard lock(_ctxMutex);        
        QueueCloser closer { queue };
        _cancelled = false;

        _history.emplace_back("user", prompt);

        struct CommitReply {
            decltype(_history)& history;
            std::string content;
            ~CommitReply() {
                history.emplace_back("assistant", std::move(content));
            }
        } reply { _history, "" };

        decodeAllHistory(true);

        llama_token next = llama_sampler_sample(_sampler.get(), _context.get(), -1);
        for (int32_t i = 0; i < maxTokens && !_cancelled; i++) {
            if (llama_vocab_is_eog(_vocab, next)) {
                break;
            }

            _committed.push_back(next);
            std::string piece = tokenToPiece(next);
            queue.push(piece);
            reply.content += piece;

            if (!decode({ next })) {
                _kvUnknown = true;
                throw std::runtime_error("decode failed");
            }

            next = llama_sampler_sample(_sampler.get(), _context.get(), -1);
        }
    }
    
    /// @copydoc ILlmBackend::cancel
    void cancel() override { _cancelled = true; }
};

std::unique_ptr<ILlmBackend> createQwen3Backend(const std::string &modelPath, int32_t contextSize) {
    return std::make_unique<Qwen3Backend>(modelPath, contextSize);
}
